In [2]:
import numpy as np
import pandas as pd 

In [3]:
pd.__version__

'2.0.3'

In [11]:
!pwsh -Command "Invoke-WebRequest -Uri https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv -OutFile housing.csv"

In [12]:
df = pd.read_csv('housing.csv')

In [21]:
df.shape

(20640, 10)

In [23]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [26]:
df['ocean_proximity']

0        NEAR BAY
1        NEAR BAY
2        NEAR BAY
3        NEAR BAY
4        NEAR BAY
           ...   
20635      INLAND
20636      INLAND
20637      INLAND
20638      INLAND
20639      INLAND
Name: ocean_proximity, Length: 20640, dtype: object

In [30]:
df[df['ocean_proximity']=='NEAR BAY']['median_house_value'].mean().round(0)

259212.0

In [39]:
mean = df['total_bedrooms'].mean()
print(mean)
print(df['total_bedrooms'].isnull().sum())
df['total_bedrooms'] = df['total_bedrooms'].fillna(mean)
print(df['total_bedrooms'].isnull().sum())


537.8705525375618
207
0


In [40]:
df['total_bedrooms'].mean()

537.8705525375617

In [57]:
islandsCond = df['ocean_proximity'] == 'ISLAND'
islands = df[islandsCond]
xdf = islands[['housing_median_age','total_rooms','total_bedrooms']]
print(xdf)
X = xdf.values

      housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0


In [58]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [59]:
XTX = X.T.dot(X)
print(XTX)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [60]:
IXTX = np.linalg.inv(XTX)
print(IXTX)

[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [61]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [66]:
w = IXTX.dot(X.T).dot(y)
print(w)

[23.12330961 -1.48124183  5.69922946]
